---
- name: "Starship | Ubuntu | Create user-local bin directory"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: "0755"

- name: "Starship | Ubuntu | Install latest release"
  ansible.builtin.shell: >-
    curl -sS https://starship.rs/install.sh |
    sh -s -- -y -b {{ ansible_env.HOME }}/.local/bin
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/starship"
    executable: /bin/sh
