---
- name: "conda | {{ ansible_distribution }} | Check if conda is installed"
  ansible.builtin.command: conda --version
  register: conda_installed
  failed_when: false
  changed_when: false

- name: "conda | {{ ansible_distribution }} | Download miniconda installer"
  ansible.builtin.get_url:
    url: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
    dest: "/tmp/miniconda.sh"
    mode: '0755'
  when: conda_installed.rc != 0

- name: "conda | {{ ansible_distribution }} |  Install miniconda"
  ansible.builtin.shell: |
    bash /tmp/miniconda.sh -b -p {{ ansible_env.HOME }}/miniconda3
  args:
    creates: "{{ ansible_env.HOME }}/miniconda3"
  when: conda_installed.rc != 0

- name: "conda | {{ ansible_distribution }} |  Initialize conda for shells"
  ansible.builtin.shell: |
    {{ ansible_env.HOME }}/miniconda3/bin/conda init bash
    {{ ansible_env.HOME }}/miniconda3/bin/conda init zsh
  when: conda_installed.rc != 0

- name: "conda | Clean up installer"
  ansible.builtin.file:
    path: "/tmp/miniconda.sh"
    state: absent
